name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the source code
      - name: Check out repository
        uses: actions/checkout@v4
        
      # Step 2: Set up the required Java version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Temurin distribution of Java
          java-version: 17       # Specify the Java version required for the project

      # Step 3: Cache Maven dependencies to speed up the build process
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2               # Directory where Maven dependencies are stored
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} # Cache key based on the OS and pom.xml file
          restore-keys: |
            ${{ runner.os }}-m2     # Fallback keys for restoring cache if the exact match is not found

      # Step 4: Build the project and run tests using Maven
      - name: Build and test with Maven
        run: mvn clean verify --batch-mode # Compile the project and run all tests
